In [1]:
def my_function():
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [8]:
assert my_sq(4) == 16

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame({
    "a": [10, 20, 30],
    "b": [20, 30, 40]
})

In [11]:
df

a   b
0  10  20
1  20  30
2  30  40

In [12]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [13]:
type(df["a"])

pandas.core.series.Series

In [14]:
my_sq

<function __main__.my_sq(x)>

In [15]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [16]:
def my_exp(x, e):
    return x ** e

In [17]:
assert my_exp(2, 2) == 4

In [18]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [19]:
df['a'].apply(lambda pizza: my_exp(2, pizza))

0          1024
1       1048576
2    1073741824
Name: a, dtype: int64

In [20]:
def print_me(x):
    print(x)

In [21]:
print_me("hello")

hello


In [23]:
df

a   b
0  10  20
1  20  30
2  30  40

In [26]:
df.apply(print_me, axis='index')

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [27]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [28]:
assert avg_3(0, 5, 10) == 5

In [30]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [33]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [34]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [35]:
import numpy as np

In [36]:
def avg_3_np(col):
    return np.mean(col)

In [37]:
df.apply(avg_3_np)

a    20.0
b    30.0
dtype: float64

In [39]:
df

a   b
0  10  20
1  20  30
2  30  40

In [38]:
df.apply(avg_3_apply, axis='columns')

IndexError: index out of bounds

In [40]:
def avg_2(x, y):
    return (x + y) / 2

In [41]:
(df['a']  + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [42]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [43]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [45]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [49]:
(df['a'] == 20)

0    False
1     True
2    False
Name: a, dtype: bool

In [50]:
(df['a'] == 20).all()

False

In [51]:
avg_2_mod(10, 20)

15.0

In [52]:
avg_2_mod(20, 30)

nan

In [53]:
df

a   b
0  10  20
1  20  30
2  30  40

In [54]:
import numpy as np

In [55]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [56]:
avg_2_mod_vec(20, 30)

array(nan)

In [57]:
avg_2_mod_vec(10, 20)

array(15.)

In [59]:
df

a   b
0  10  20
1  20  30
2  30  40

In [58]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [61]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [62]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [63]:
import numba

In [86]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [87]:
v_avg_2_mod_numba(df['a'], df['b'])

ValueError: cannot determine Numba type of <class 'pandas.core.series.Series'>

In [88]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [89]:
%%timeit
avg_2(df['a'], df['b'])

645 µs ± 73.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [90]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

163 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [91]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

14.2 µs ± 1.73 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [95]:
tbl3 = pd.read_csv(("../data/table3.csv"))

In [96]:
tbl3

country  year               rate
0  Afghanistan  1999       745/19987071
1  Afghanistan  2000      2666/20595360
2       Brazil  1999    37737/172006362
3       Brazil  2000    80488/174504898
4        China  1999  212258/1272915272
5        China  2000  213766/1280428583

Write a function that takes a value of rate and parses out the total population

Set the population to a new column

In [99]:
"745/19987071".split("/")[1]

'19987071'

In [100]:
def get_pop(rate):
    return int(rate.split("/")[1])

In [101]:
get_pop("745/19987071")

19987071

In [102]:
@np.vectorize
def get_pop(rate):
    return int(rate.split("/")[1])

In [103]:
tbl3['population'] = get_pop(tbl3['rate'])

In [104]:
tbl3

country  year               rate  population
0  Afghanistan  1999       745/19987071    19987071
1  Afghanistan  2000      2666/20595360    20595360
2       Brazil  1999    37737/172006362   172006362
3       Brazil  2000    80488/174504898   174504898
4        China  1999  212258/1272915272  1272915272
5        China  2000  213766/1280428583  1280428583

In [105]:
tbl3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   country     6 non-null      object
 1   year        6 non-null      int64 
 2   rate        6 non-null      object
 3   population  6 non-null      int32 
dtypes: int32(1), int64(1), object(2)
memory usage: 296.0+ bytes
